# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: "Merlin CLI Build & Test"

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '.github/**'
      - '.qodana/**'
      - 'docs/**'
      - '.gitattributes'
      - '.gitignore'
      - 'Dockerfile'
      - 'go.mod'
      - 'go.sum'
      - 'LICENSE'
      - 'Makefile'
      - 'qodana.yaml'
      - 'README.MD'
  pull_request:
    paths-ignore:
      - '.github/**'
      - '.qodana/**'
      - 'docs/**'
      - '.gitattributes'
      - '.gitignore'
      - 'Dockerfile'
      - 'go.mod'
      - 'go.sum'
      - 'LICENSE'
      - 'Makefile'
      - 'qodana.yaml'
      - 'README.MD'

jobs:

  build:
    name: 'Build Job'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        id: checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          check-latest: true

      - name: 'Build Merlin CLI'
        id: build
        run: 'make all'

      - name: 'Test Merlin CLI'
        id: test
        run: 'go test ./...'
