name: "Qodana: Pull Request"

on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - '.github/**'
      - '.qodana/**'
      - 'data/**'
      - 'docs/**'
      - '.gitattributes'
      - '.gitignore'
      - '.gitmodules'
      - 'Dockerfile'
      - 'LICENSE'
      - 'Makefile'
      - 'qodana.yaml'
      - 'README.MD'

jobs:
  qodana:
    name: 'Qodana Job'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}  # to check out the actual pull request commit, not the merge commit
          fetch-depth: 0  # a full history is required for pull request analysis
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2023.3
        with:
          args: -l,jetbrains/qodana-go:2023.3-eap,--baseline,.qodana/qodana.sarif.json
          pr-mode: false