name: "Qodana: Push"
on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '.github/**'
      - '.qodana/**'
      - 'docs/**'
      - '.gitattributes'
      - '.gitignore'
      - 'Dockerfile'
      - 'go.mod'
      - 'go.sum'
      - 'LICENSE'
      - 'Makefile'
      - 'qodana.yaml'
      - 'README.MD'

jobs:
  qodana:
    name: 'Qodana Job'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}  # to check out the actual pull request commit, not the merge commit
          fetch-depth: 0  # a full history is required for pull request analysis
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2023.3
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
        with:
          args: --baseline,.qodana/qodana.sarif.json
